services:
  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    container_name: resume-make
    entrypoint: /entrypoint.sh
    image: resume-make
    volumes:
      - /home/stev/Documents/pandoc_resume/:/data
